name: Procesar Costos Allix
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Librerias
        run: pip install pandas openpyxl

      - name: Ejecutar Script
        run: python transformar.py

      - name: Guardar Resultado
        uses: actions/upload-artifact@v3
        with:
          name: Reporte-Costos-Final
          path: RESULTADO_COMPARATIVO.xlsx
